import type { NextPage } from 'next'
import Head from 'next/head'
import { ComponentPropsWithoutRef, ReactNode } from 'react'

import Link from 'next/link'
import { FaGithub } from 'react-icons/fa'

type InputProps = {
    label: ReactNode
} & ComponentPropsWithoutRef<'input'>

const Input = ({ label, ...props }: InputProps) => {
    return (
        <div className="flex flex-col">
            <label className="text-sm" htmlFor={props.name}>
                {label}
            </label>
            <input {...props} className="border rounded px-2 py-1 focus:border-red-500" />
        </div>
    )
}

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Teapot chat</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container flex flex-col items-center min-h-screen py-16 mx-auto bg-gray-50">
                <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
                    Tea<span className="text-indigo-500">pot</span> Chat
                </h1>

                <div className="shadow-md p-4 rounded bg-white my-2 w-full max-w-xs">
                    <section>
                        <h2>Log in using: </h2>
                        <button className="text-3xl p-2">
                            <FaGithub />
                        </button>
                    </section>
                    <hr className="my-4" />
                    <section>
                        <h2>Log in using email</h2>
                        <form className="flex flex-col space-y-2" onSubmit={(e) => e.preventDefault()}>
                            <Input label="Email" />
                            <Input label="Password" type={'password'} />
                            <button className="bg-indigo-500 py-1 px-4 text-white rounded">Log in</button>
                        </form>
                    </section>
                </div>

                <section>
                    <span>
                        {'First time? '}
                        <Link href={'/register'}>
                            <a className="text-indigo-500 hover:underline">Register now</a>
                        </Link>
                    </span>
                </section>
            </main>
        </>
    )
}

export default Home
